#include "journal.h"
#include <stdio.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <unistd.h>
#include <assert.h>
#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include <pthread.h>
#include <sys/stat.h>
#include <sys/file.h>

/**
 * Rule of thumb:
 * 
 *   - We use FILE and fwrite() to write to files. 
 *     These methods are buffered and faster than write() system call.
 *   - We use file descriptor and read() to read from files.
 *     We rely on the filesystem cache for buffering.
 */

#define LDB_EXT_DAT             ".dat"
#define LDB_EXT_IDX             ".idx"
#define LDB_PATH_SEPARATOR      "/"
#define LDB_NAME_MAX_LENGTH     32

#define LDB_STR_HELPER(x)  #x
#define LDB_STR(x)         LDB_STR_HELPER(x)

#define LDB_FREE_STR(ptr) do { free(ptr); ptr = NULL; } while (0)
#define exit_function(retval) do { ret = retval; goto END_FUNCTION; } while (0)

#if defined(__GNUC__) || defined(__clang__) || defined(__INTEL_LLVM_COMPILER)
    #define LDB_PACKED  __attribute__((__packed__))
#else
    #define LDB_PACKED  /**/
#endif

typedef struct ldb_impl_t
{
    // Fixed data (unchanged)
    char *name;                   // Journal name
    char *path;                   // Directory where files are located
    char *dat_path;               // Data filepath (path + filename)
    char *idx_path;               // Index filepath (path + filename)
    uint32_t format;              // File format
    bool force_fsync;             // Force fsync after flush
    bool read_only;               // Journal opened in read-only mode

    // Shared data (accessed by both threads)
    pthread_mutex_t mutex_state;  // Prevents race condition on state values
    pthread_mutex_t mutex_files;  // Preserve coherence between shared variable and file contents
    ldb_range_t state;            // First and last seqnums
    FILE *dat_fp;                 // Data file pointer (used to write)
    FILE *idx_fp;                 // Index file pointer (used to write)

    // Thread-write variables
    char padding[64];             // Padding to avoid destructive interference between threads
    size_t dat_end;               // Last position on data file

} ldb_impl_t;

typedef struct LDB_PACKED ldb_header_dat_t {
    uint64_t magic_number;
    uint32_t format;
    uint32_t padding;
    char metadata[LDB_METADATA_LEN];
} ldb_header_dat_t;

typedef struct LDB_PACKED ldb_header_idx_t {
    uint64_t magic_number;
    uint32_t format;
    uint32_t padding;
    uint64_t first_seqnum;
} ldb_header_idx_t;

typedef struct LDB_PACKED ldb_record_dat_t {
    uint64_t seqnum;
    uint32_t data_len;
    uint32_t checksum;
} ldb_record_dat_t;

typedef struct LDB_PACKED ldb_record_idx_t {
    uint64_t pos;
} ldb_record_idx_t;

#include <nmmintrin.h>
/**
 * Generated by https://github.com/corsix/fast-crc32/
 * Using: ./generate -i sse -p crc32c
 * License: MIT or zlib licensed
 */
__attribute__((target("sse4.2,pclmul")))
static uint32_t ldb_crc32(const char* buf, size_t len, uint32_t crc0)
{
    if (buf == NULL || len == 0)
        return crc0;

    crc0 = ~crc0;

    for (; len && ((uintptr_t)buf & 7); --len)
        crc0 = _mm_crc32_u8(crc0, *buf++);

    for (; len >= 8; buf += 8, len -= 8)
        crc0 = _mm_crc32_u64(crc0, *(const uint64_t*)buf);

    for (; len; --len)
        crc0 = _mm_crc32_u8(crc0, *buf++);

    return ~crc0;
}

const char * ldb_strerror(int errnum)
{
    if (errnum > 0)
        return "Success";

    switch (errnum)
    {
        case LDB_OK:                    return "Success";
        case LDB_ERR:                   return "Generic error";
        case LDB_ERR_ARG:               return "Invalid argument";
        case LDB_ERR_MEM:               return "Out of memory";
        case LDB_ERR_PATH:              return "Invalid directory";
        case LDB_ERR_NAME:              return "Invalid journal name";
        case LDB_ERR_READONLY:          return "Journal is read-only";
        case LDB_ERR_NOFILE_DAT:        return "Dat file not found";
        case LDB_ERR_NOFILE_IDX:        return "Idx file not found";
        case LDB_ERR_INVL_DAT:          return "Invalid dat file";
        case LDB_ERR_INVL_IDX:          return "Invalid idx file";
        case LDB_ERR_CORRUPT_DAT:       return "Corrupted dat file";
        case LDB_ERR_CORRUPT_IDX:       return "Corrupted idx file";
        case LDB_ERR_CREATE_DAT:        return "Error creating dat file";
        case LDB_ERR_CREATE_IDX:        return "Error creating idx file";
        case LDB_ERR_OPEN_DAT:          return "Cannot open dat file";
        case LDB_ERR_OPEN_IDX:          return "Cannot open idx file";
        case LDB_ERR_READ_DAT:          return "Error reading dat file";
        case LDB_ERR_READ_IDX:          return "Error reading idx file";
        case LDB_ERR_WRITE_DAT:         return "Error writing to dat file";
        case LDB_ERR_WRITE_IDX:         return "Error writing to idx file";
        case LDB_ERR_SEQNUM:            return "Broken sequence";
        case LDB_ERR_NODATA:            return "Data not found";
        case LDB_ERR_CHECKSUM:          return "Checksum mismatch";
        case LDB_ERR_NOT_FOUND:         return "No results";
        case LDB_ERR_LOCK:              return "Error locking file";
        default:                        return "Unknown error";
    }
}

static inline size_t ldb_min(size_t a, size_t b) {
    return (a < b ? a : b);
}

static inline uint64_t ldb_max(uint64_t a, uint64_t b) {
    return (a > b ? a : b);
}

static inline size_t ldb_padding(size_t value) {
    size_t round_up = (value + (sizeof(uintptr_t) - 1)) & ~(sizeof(uintptr_t) - 1);
    return round_up - value;
}

static inline bool ldb_is_valid_obj(ldb_impl_t *obj) {
    return (obj &&
            obj->dat_fp && !feof(obj->dat_fp) && !ferror(obj->dat_fp) &&
            obj->idx_fp && !feof(obj->idx_fp) && !ferror(obj->idx_fp));
}

static void ldb_reset_state(ldb_range_t *state) {
    if (state) {
        state->min_seqnum = 0;
        state->max_seqnum = 0;
    }
}

static int ldb_close_files(ldb_impl_t *obj)
{
    if (!obj)
        return LDB_OK;

    int ret = LDB_OK;

    if (obj->idx_fp != NULL)
    {
        int idx_fd = fileno(obj->idx_fp);

        if (!obj->read_only)
            flock(idx_fd, LOCK_UN);

        if (fclose(obj->idx_fp) != 0)
            ret = LDB_ERR_WRITE_IDX;

        obj->idx_fp = NULL;
    }

    if (obj->dat_fp != NULL)
    {
        int dat_fd = fileno(obj->dat_fp);

        if (!obj->read_only)
            flock(dat_fd, LOCK_UN);

        if (fclose(obj->dat_fp) != 0)
            ret = LDB_ERR_WRITE_DAT;

        obj->dat_fp = NULL;
    }

    obj->dat_end = 0;

    return ret;
}

int ldb_close(ldb_impl_t *obj)
{
    if (obj == NULL)
        return LDB_OK;

    int ret = ldb_close_files(obj);

    ldb_reset_state(&obj->state);

    if (obj->name) {
        pthread_mutex_destroy(&obj->mutex_state);
        pthread_mutex_destroy(&obj->mutex_files);
    }

    LDB_FREE_STR(obj->name);
    LDB_FREE_STR(obj->path);
    LDB_FREE_STR(obj->dat_path);
    LDB_FREE_STR(obj->idx_path);

    return ret;
}

static bool ldb_is_valid_path(const char *path)
{
    struct stat statbuf = {0};

    if (path == NULL)
        return false;

    if (*path == 0)  // case cwd (current working directory)
        return true;

    if (stat(path, &statbuf) != 0 || !S_ISDIR(statbuf.st_mode))
        return false;

    return true;
}

static bool ldb_is_valid_name(const char *name)
{
    if (!name || *name == 0)
        return false;

    const char *ptr = name;

    if (!isalnum((unsigned char)*ptr) && strchr("_-", *ptr) == NULL)
        return false;

    ptr++;

    while (*ptr != 0 && (isalnum((unsigned char)*ptr) || strchr("_-", *ptr) != NULL))
        ptr++;

    return (*ptr == 0 && ptr - name <= LDB_NAME_MAX_LENGTH);
}

static char * ldb_create_filename(const char *path, const char *name, const char *ext)
{
    if (path == NULL || name == NULL || ext == NULL || *name == 0)
        return NULL;

    size_t len = strlen(path);
    bool path_sep_required = (len > 0 && path[len - 1] != LDB_PATH_SEPARATOR[0]);

    len = len + 1 + strlen(name) + strlen(ext) + 1;
    char *filepath = (char *)calloc(len, 1);

    if (filepath == NULL)
        return NULL;

    snprintf(filepath, len, "%s%s%s%s",
             path,
             (path_sep_required ? LDB_PATH_SEPARATOR : ""),
             name,
             ext);

    return filepath;
}

static int ldb_init(ldb_impl_t *obj, const char *path, const char *name, int flags)
{
    if (obj == NULL)
        return LDB_ERR_ARG;

    if (!ldb_is_valid_path(path))
        return LDB_ERR_PATH;

    if (!ldb_is_valid_name(name))
        return LDB_ERR_NAME;

    memset(obj, 0x00, sizeof(ldb_impl_t));

    obj->name = strdup(name);
    obj->path = strdup(path);
    obj->dat_path = ldb_create_filename(path, name, LDB_EXT_DAT);
    obj->idx_path = ldb_create_filename(path, name, LDB_EXT_IDX);

    if (!obj->name || !obj->path || !obj->dat_path || !obj->idx_path) {
        LDB_FREE_STR(obj->name);
        LDB_FREE_STR(obj->path);
        LDB_FREE_STR(obj->dat_path);
        LDB_FREE_STR(obj->idx_path);
        return LDB_ERR_MEM;
    }

    pthread_mutex_init(&obj->mutex_state, NULL);
    pthread_mutex_init(&obj->mutex_files, NULL);

    obj->force_fsync = ((flags & LDB_OPEN_FSYNC) != 0);
    obj->read_only = ((flags & LDB_OPEN_READONLY) != 0);
    obj->dat_end = sizeof(ldb_header_dat_t);

    return LDB_OK;
}

// Create a new dat file
// Returns error if the file already exists
static bool ldb_create_dat(const char *path)
{
    assert(path);

    if (access(path, F_OK) == 0)
        return false;

    bool ret = true;

    FILE *fp = fopen(path, "wx");
    if (fp == NULL)
        return false;

    ldb_header_dat_t header = {
        .magic_number = LDB_DAT_MAGIC_NUMBER,
        .format = LDB_FILE_FORMAT,
        .padding = 0,
        .metadata = {0}
    };

    if (fwrite(&header, sizeof(ldb_header_dat_t), 1, fp) != 1)
        ret = false;

    if (fclose(fp) != 0)
        ret = false;

    return ret;
}

// Create a new idx file
// Returns error if the file already exists
static bool ldb_create_idx(const char *path)
{
    assert(path);

    if (access(path, F_OK) == 0)
        return false;

    bool ret = true;

    FILE *fp = fopen(path, "wx");
    if (fp == NULL)
        return false;

    ldb_header_idx_t header = {
        .magic_number = LDB_IDX_MAGIC_NUMBER,
        .format = LDB_FILE_FORMAT,
        .padding = 0,
        .first_seqnum = 0
    };

    if (fwrite(&header, sizeof(ldb_header_idx_t), 1, fp) != 1)
        ret = false;

    if (fclose(fp) != 0)
        ret = false;

    return ret;
}

// Returns file size preserving current file position
// Returns 0 on error
static size_t ldb_get_file_size(FILE *fp)
{
    if (fp == NULL)
        return 0;

    long pos = ftell(fp);
    if (pos < 0)
        return 0;

    if (fseek(fp, 0, SEEK_END) != 0)
        return 0;

    long len = ftell(fp);

    if (fseek(fp, pos, SEEK_SET) != 0)
        return 0;

    return (size_t)(len < 0 ? 0 : len);
}

static bool ldb_is_zeroized(FILE *fp, size_t pos)
{
    assert(fp);
    assert(!feof(fp));
    assert(!ferror(fp));

    const char buf_zeros[BUFSIZ] = {0};
    char read_buf[BUFSIZ] = {0};
    size_t max_pos = ldb_get_file_size(fp);

    if (max_pos < pos)
        return false;

    if (fseek(fp, (long)pos, SEEK_SET) != 0)
        return false;

    if (max_pos == pos)
        return true;

    for (size_t cur_pos = pos; cur_pos < max_pos; cur_pos += BUFSIZ)
    {
        size_t num_bytes = ldb_min(max_pos - cur_pos, BUFSIZ);

        if (fread(read_buf, 1, num_bytes, fp) != num_bytes)
            return false;

        if (memcmp(buf_zeros, read_buf, num_bytes) != 0)
            return false;
    }

    if (fseek(fp, (long)pos, SEEK_SET) != 0)
        return false;

    assert(!feof(fp) && !ferror(fp));
    return true;
}

// Set zero's from pos until the end of the file.
// At return file position is set at pos.
// On error return false, otherwise returns true.
static bool ldb_zeroize(FILE *fp, size_t pos)
{
    assert(fp);
    assert(!feof(fp));
    assert(!ferror(fp));

    const char buf[BUFSIZ] = {0};
    size_t max_pos = ldb_get_file_size(fp);

    if (max_pos < pos)
        return false;

    if (fseek(fp, (long)pos, SEEK_SET) != 0)
        return false;

    if (max_pos == pos)
        return true;

    for (size_t cur_pos = pos; cur_pos < max_pos; cur_pos += sizeof(buf))
        if (fwrite(buf, ldb_min(max_pos - cur_pos, sizeof(buf)), 1, fp) != 1)
            return false;

    if (fflush(fp) != 0)
        return false;

    if (fseek(fp, (long)pos, SEEK_SET) != 0)
        return false;

    assert(!feof(fp) && !ferror(fp));
    return true;
}

// Copy file1 content in range [pos0,pos1] to file2 at pos2.
// Preserve current file positions.
// Flush destination file.
// On error return false, otherwise returns true.
static bool ldb_copy_file(FILE *fp1, size_t pos0, size_t pos1, FILE *fp2, size_t pos2)
{
    assert(fp1);
    assert(!feof(fp1));
    assert(!ferror(fp1));
    assert(fp2);
    assert(!feof(fp2));
    assert(!ferror(fp2));
    assert(pos0 <= pos1);

    size_t len1 = ldb_get_file_size(fp1);
    size_t len2 = ldb_get_file_size(fp2);

    if (pos0 > pos1 || pos1 > len1 || pos2 > len2)
        return false;

    if (pos0 == pos1)
        return true;

    int fd1 = fileno(fp1);
    int fd2 = fileno(fp2);

    if (fd1 == -1 || fd2 == -1)
        return false;

    // Flush fp2 stdio buffer before writing via raw fd
    if (fflush(fp2) != 0)
        return false;

    off_t off_in  = (off_t)pos0;
    off_t off_out = (off_t)pos2;
    size_t remaining = pos1 - pos0;

    while (remaining > 0)
    {
        ssize_t rc = copy_file_range(fd1, &off_in, fd2, &off_out, remaining, 0);

        if (rc <= 0)
            return false;

        remaining -= (size_t)rc;
    }

    return true;
}

// returns the position in the idx file for a given seqnum
static size_t ldb_get_pos_idx(ldb_range_t *state, uint64_t seqnum)
{
    assert(state);
    assert(state->min_seqnum <= seqnum);

    size_t diff = (state->min_seqnum == 0 ? 0 : seqnum - state->min_seqnum);
    return sizeof(ldb_header_idx_t) + diff * sizeof(ldb_record_idx_t);
}

static uint32_t ldb_checksum_record(ldb_record_dat_t *record)
{
    uint32_t checksum = 0;

    checksum = ldb_crc32((const char *)&record->seqnum, sizeof(record->seqnum), checksum);
    checksum = ldb_crc32((const char *)&record->data_len, sizeof(record->data_len), checksum);

    // required call to complete the checksum
    // call checksum = crc32(data, checksum)

    return checksum;
}

static uint32_t ldb_checksum_entry(ldb_entry_t *entry)
{
    uint32_t checksum = 0;

    checksum = ldb_crc32((const char *)&entry->seqnum, sizeof(entry->seqnum), checksum);
    checksum = ldb_crc32((const char *)&entry->data_len, sizeof(entry->data_len), checksum);

    if (entry->data_len && entry->data)
        checksum = ldb_crc32((const char *)entry->data, entry->data_len, checksum);

    return checksum;
}

// append data entry at position obj->dat_end
// updates obj->dat_end value
// function accessed only by thread-write
static int ldb_append_entry_dat(ldb_impl_t *obj, ldb_range_t *state, ldb_entry_t *entry)
{
    assert(obj);
    assert(state);
    assert(entry);
    assert(obj->dat_fp);
    assert(!feof(obj->dat_fp));
    assert(!ferror(obj->dat_fp));

    static const char zeros[sizeof(uintptr_t)] = {0};

    if (entry->data_len != 0 && entry->data == NULL)
        return LDB_ERR_NODATA;

    if (state->max_seqnum != 0 && entry->seqnum != state->max_seqnum + 1)
        return LDB_ERR_SEQNUM;

    ldb_record_dat_t record = {
        .seqnum = entry->seqnum,
        .data_len = entry->data_len,
        .checksum = ldb_checksum_entry(entry)
    };

    if (fwrite(&record, sizeof(ldb_record_dat_t), 1, obj->dat_fp) != 1)
        return LDB_ERR_WRITE_DAT;

    if (record.data_len)
    {
        if (fwrite(entry->data, 1, record.data_len, obj->dat_fp) != record.data_len)
            return LDB_ERR_WRITE_DAT;

        size_t padding = ldb_padding(entry->data_len);

        if (fwrite(zeros, 1, padding, obj->dat_fp) != padding)
            return LDB_ERR_WRITE_DAT;
    }

    if (state->min_seqnum == 0)
        state->min_seqnum = entry->seqnum;

    state->max_seqnum = entry->seqnum;

    long pos = ftell(obj->dat_fp);
    if (pos < 0)
        return LDB_ERR_READ_DAT;

    obj->dat_end = (size_t)pos;

    return LDB_OK;
}

static int ldb_write_idx_seqnum(ldb_impl_t *obj, uint64_t seqnum)
{
    assert(obj);
    assert(obj->idx_fp);

    int fd = fileno(obj->idx_fp);
    off_t pos = offsetof(ldb_header_idx_t, first_seqnum);

    if (fd == -1)
        return LDB_ERR_WRITE_IDX;

    if (pwrite(fd, &seqnum, sizeof(seqnum), pos) != (ssize_t)sizeof(seqnum))
        return LDB_ERR_WRITE_IDX;

    return LDB_OK;
}

static int ldb_append_record_idx(ldb_impl_t *obj, ldb_range_t *state, ldb_record_idx_t *record)
{
    assert(obj);
    assert(state);
    assert(record);
    assert(obj->idx_fp);
    assert(!feof(obj->idx_fp));
    assert(!ferror(obj->idx_fp));

    if (fwrite(record, sizeof(ldb_record_idx_t), 1, obj->idx_fp) != 1)
        return LDB_ERR_WRITE_IDX;

    // first record: persist first_seqnum in the header
    if (state->min_seqnum == state->max_seqnum)
    {
        if (ldb_write_idx_seqnum(obj, state->min_seqnum) != LDB_OK)
            return LDB_ERR_WRITE_IDX;
    }

    return LDB_OK;
}

// Read data record at pos.
// File position is not modified.
static int ldb_read_record_dat(int fd, size_t pos, ldb_record_dat_t *record, bool verify_checksum)
{
    assert(record);
    assert(fd > STDERR_FILENO);

    ssize_t rc = pread(fd, record, sizeof(ldb_record_dat_t), (off_t)pos);

    if (rc == -1)
        return LDB_ERR_READ_DAT;

    if (rc != sizeof(ldb_record_dat_t))
        return LDB_ERR_CORRUPT_DAT;

    if (!verify_checksum || record->seqnum == 0)
        return LDB_OK;

    uint32_t checksum = ldb_checksum_record(record);
    size_t len = record->data_len;

    if (len > 0)
    {
        pos += sizeof(ldb_record_dat_t);

        char buf[BUFSIZ] = {0};
        size_t end = pos + len;

        while (pos < end)
        {
            size_t num_bytes = ldb_min(end - pos, sizeof(buf));

            rc = pread(fd, buf, num_bytes, (off_t)pos);

            if (rc == -1)
                return LDB_ERR_READ_DAT;

            if (rc != (ssize_t)num_bytes)
                return LDB_ERR_CORRUPT_DAT;

            pos += num_bytes;

            checksum = ldb_crc32(buf, num_bytes, checksum);
        }
    }

    if (checksum != record->checksum)
        return LDB_ERR_CHECKSUM;

    return LDB_OK;
}

// Read idx record at pos.
// File position is not modified.
static int ldb_read_record_idx(int fd, ldb_range_t *state, uint64_t seqnum, ldb_record_idx_t *record)
{
    assert(state);
    assert(record);
    assert(fd > STDERR_FILENO);

    if (state->min_seqnum == 0 || seqnum < state->min_seqnum || state->max_seqnum < seqnum)
        return LDB_ERR_NOT_FOUND;

    ssize_t rc = 0;
    size_t pos = ldb_get_pos_idx(state, seqnum);

    rc = pread(fd, record, sizeof(ldb_record_idx_t), (off_t)pos);

    if (rc == -1)
        return LDB_ERR_READ_IDX;

    if (rc != (ssize_t)sizeof(ldb_record_idx_t))
        return LDB_ERR_CORRUPT_IDX;

    return LDB_OK;
}

/**
 * Opens the dat file and reads the first record.
 * No validation of remaining records, no repair.
 *
 * post-conditions (OK)
 *   - obj->dat_fp = set (file position at end)
 *   - obj->format = set
 *   - obj->state.min_seqnum = set (0 if no data)
 *
 * post-conditions (KO)
 *   - dat file closed
 */
static int ldb_open_dat(ldb_impl_t *obj)
{
    assert(obj);
    assert(obj->dat_fp == NULL);
    assert(obj->idx_fp == NULL);

    ssize_t rc = 0;
    int ret = LDB_OK;
    int dat_fd = -1;
    ldb_header_dat_t header = {0};
    ldb_record_dat_t record = {0};
    size_t pos = 0;
    size_t len = 0;

    ldb_reset_state(&obj->state);
    obj->dat_end = sizeof(ldb_header_dat_t);

    obj->dat_fp = fopen(obj->dat_path, obj->read_only ? "r" : "r+");

    if (obj->dat_fp == NULL)
        return LDB_ERR_OPEN_DAT;

    if ((dat_fd = fileno(obj->dat_fp)) == -1)
        exit_function(LDB_ERR_OPEN_DAT);

    if (!obj->read_only && flock(dat_fd, LOCK_EX | LOCK_NB) == -1)
        exit_function(LDB_ERR_LOCK);

    len = ldb_get_file_size(obj->dat_fp);

    rc = pread(dat_fd, &header, sizeof(ldb_header_dat_t), 0);

    if (rc == -1)
        exit_function(LDB_ERR_READ_DAT);

    if (rc != (ssize_t)sizeof(ldb_header_dat_t))
        exit_function(LDB_ERR_INVL_DAT);

    pos += sizeof(ldb_header_dat_t);

    if (header.magic_number != LDB_DAT_MAGIC_NUMBER)
        exit_function(LDB_ERR_INVL_DAT);

    if (header.format != LDB_FILE_FORMAT)
        exit_function(LDB_ERR_INVL_DAT);

    obj->format = header.format;

    // read first entry (if any)
    if (pos + sizeof(ldb_record_dat_t) <= len)
    {
        ret = ldb_read_record_dat(dat_fd, pos, &record, true);

        if (ret == LDB_OK && record.seqnum != 0)
        {
            obj->state.min_seqnum = record.seqnum;
        }
    }

    if (fseek(obj->dat_fp, 0, SEEK_END) == -1)
        exit_function(LDB_ERR_READ_DAT);

    return LDB_OK;

END_FUNCTION:
    ldb_close_files(obj);
    ldb_reset_state(&obj->state);
    return ret;
}

/**
 * Opens the idx file and determines journal state from existing idx records.
 * Uses backwards search to find the last valid idx record.
 * No full validation, no repair, no writes.
 *
 * post-conditions (OK)
 *   - obj->idx_fp = set (file position at end)
 *   - obj->state.max_seqnum = set (0 if no data or idx empty)
 *   - obj->dat_end = set
 *
 * post-conditions (KO)
 *   - idx file closed
 */
static int ldb_open_idx(ldb_impl_t *obj)
{
    assert(obj);
    assert(obj->idx_fp == NULL);
    assert(obj->dat_fp != NULL);
    assert(!ferror(obj->dat_fp) && !feof(obj->dat_fp));

    ssize_t rc = 0;
    int ret = LDB_OK;
    int dat_fd = -1;
    int idx_fd = -1;
    ldb_header_idx_t header = {0};
    ldb_record_idx_t record_0 = {0};
    ldb_record_idx_t record_n = {0};
    ldb_record_dat_t record_dat = {0};
    size_t pos = 0;
    size_t len = 0;

    if ((dat_fd = fileno(obj->dat_fp)) == -1)
        return LDB_ERR_OPEN_DAT;

    obj->idx_fp = fopen(obj->idx_path, obj->read_only ? "r" : "r+");

    if (obj->idx_fp == NULL)
        return LDB_ERR_OPEN_IDX;

    if ((idx_fd = fileno(obj->idx_fp)) == -1)
        exit_function(LDB_ERR_OPEN_IDX);

    if (!obj->read_only && flock(idx_fd, LOCK_EX | LOCK_NB) == -1)
        exit_function(LDB_ERR_LOCK);

    len = ldb_get_file_size(obj->idx_fp);

    rc = pread(idx_fd, &header, sizeof(ldb_header_idx_t), 0);

    if (rc == -1)
        exit_function(LDB_ERR_READ_IDX);

    if (rc != (ssize_t)sizeof(ldb_header_idx_t))
        exit_function(LDB_ERR_INVL_IDX);

    pos += sizeof(ldb_header_idx_t);

    if (header.magic_number != LDB_IDX_MAGIC_NUMBER)
        exit_function(LDB_ERR_INVL_IDX);

    if (header.format != LDB_FILE_FORMAT)
        exit_function(LDB_ERR_INVL_IDX);

    if (header.format != obj->format)
        exit_function(LDB_ERR_INVL_IDX);

    // cross-check first_seqnum against dat
    if (header.first_seqnum != obj->state.min_seqnum)
        exit_function(LDB_ERR_CORRUPT_IDX);

    // read first idx record (if any)
    if (pos + sizeof(ldb_record_idx_t) <= len)
    {
        rc = pread(idx_fd, &record_0, sizeof(ldb_record_idx_t), (off_t)pos);

        if (rc == -1)
            exit_function(LDB_ERR_READ_IDX);

        if (rc != (ssize_t)sizeof(ldb_record_idx_t))
            exit_function(LDB_ERR_CORRUPT_IDX);

        if (header.first_seqnum != 0 && record_0.pos != sizeof(ldb_header_dat_t))
            exit_function(LDB_ERR_CORRUPT_IDX);
    }

    record_n = record_0;

    if (header.first_seqnum != 0)
    {
        // backwards search for last non-zero record
        long rem = ((long)len - (long)sizeof(ldb_header_idx_t)) % (int)sizeof(ldb_record_idx_t);
        pos = len - (size_t)(rem);

        while (pos > sizeof(ldb_header_idx_t))
        {
            off_t new_pos = (off_t)(pos - sizeof(ldb_record_idx_t));

            rc = pread(idx_fd, &record_n, sizeof(ldb_record_idx_t), new_pos);

            if (rc == -1)
                exit_function(LDB_ERR_READ_IDX);

            if (rc != (ssize_t)sizeof(ldb_record_idx_t))
                exit_function(LDB_ERR_CORRUPT_IDX);

            pos -= sizeof(ldb_record_idx_t);

            if (record_n.pos != 0)
                break;
        }

        // derive last seqnum from its position in the idx file
        uint64_t last_seqnum = header.first_seqnum + (pos - sizeof(ldb_header_idx_t)) / sizeof(ldb_record_idx_t);

        if (ldb_read_record_dat(dat_fd, record_n.pos, &record_dat, true) != LDB_OK)
            exit_function(LDB_ERR_CORRUPT_IDX);

        // validate content against dat
        if (record_dat.seqnum != last_seqnum)
            exit_function(LDB_ERR_CORRUPT_IDX);

        obj->state.max_seqnum = last_seqnum;
        obj->dat_end = record_n.pos + sizeof(ldb_record_dat_t) + record_dat.data_len + ldb_padding(record_dat.data_len);

        // verify no unindexed entries remain in dat after the last indexed entry
        if (ldb_read_record_dat(dat_fd, obj->dat_end, &record_dat, true) == LDB_OK) {
            if (record_dat.seqnum == obj->state.max_seqnum + 1)
                exit_function(LDB_ERR_CORRUPT_IDX);
        }
    }

    // case no data
    if (obj->state.min_seqnum == 0)
        obj->dat_end = sizeof(ldb_header_dat_t);

    if (fseek(obj->idx_fp, 0, SEEK_END) == -1)
        exit_function(LDB_ERR_READ_IDX);

    return LDB_OK;

END_FUNCTION:
    if (obj->idx_fp != NULL) fclose(obj->idx_fp);
    obj->idx_fp = NULL;
    return ret;
}

/**
 * Rebuilds the idx file from the dat file contents.
 * Caller must hold mutex_files (or guarantee exclusive access).
 * On success: idx_fp is open (at end), state and dat_end are updated.
 * On error: idx_fp may be NULL, state may be inconsistent.
 *
 * pre-conditions:
 *   - obj->dat_fp = open and valid
 *
 * post-conditions (OK):
 *   - obj->idx_fp = set (file position at end)
 *   - obj->state = updated from dat scan
 *   - obj->dat_end = updated
 */
static int ldb_rebuild_idx(ldb_impl_t *obj)
{
    assert(obj);
    assert(obj->dat_fp != NULL);
    assert(!feof(obj->dat_fp) && !ferror(obj->dat_fp));

    int ret = LDB_OK;
    int dat_fd = fileno(obj->dat_fp);
    int idx_fd = -1;
    ldb_record_dat_t record_dat = {0};
    ldb_record_idx_t record_idx = {0};
    ldb_range_t new_state = {0};
    size_t pos = sizeof(ldb_header_dat_t);
    size_t dat_len = ldb_get_file_size(obj->dat_fp);
    size_t valid_end = sizeof(ldb_header_dat_t);

    // Step 1: Close and recreate idx
    if (obj->idx_fp != NULL)
    {
        fclose(obj->idx_fp);
        obj->idx_fp = NULL;
    }

    assert(obj->idx_path);
    remove(obj->idx_path);

    if (!ldb_create_idx(obj->idx_path))
        exit_function(LDB_ERR_CREATE_IDX);

    obj->idx_fp = fopen(obj->idx_path, "r+");

    if (obj->idx_fp == NULL)
        exit_function(LDB_ERR_OPEN_IDX);

    if ((idx_fd = fileno(obj->idx_fp)) == -1)
        exit_function(LDB_ERR_OPEN_IDX);

    if (flock(idx_fd, LOCK_EX | LOCK_NB) == -1)
        exit_function(LDB_ERR_LOCK);

    if (fseek(obj->idx_fp, sizeof(ldb_header_idx_t), SEEK_SET) == -1)
        exit_function(LDB_ERR_READ_IDX);

    // Step 2: Scan dat and write idx in a single pass
    while (pos + sizeof(ldb_record_dat_t) <= dat_len)
    {
        ret = ldb_read_record_dat(dat_fd, pos, &record_dat, true);

        if (ret != LDB_OK)
            break;

        if (record_dat.seqnum == 0)
            break;

        if (new_state.max_seqnum != 0 && record_dat.seqnum != new_state.max_seqnum + 1)
            break;

        size_t rec_len = sizeof(ldb_record_dat_t) + record_dat.data_len + ldb_padding(record_dat.data_len);

        if (pos + rec_len > dat_len)
            break;

        if (new_state.min_seqnum == 0)
        {
            new_state.min_seqnum = record_dat.seqnum;
        }

        new_state.max_seqnum = record_dat.seqnum;

        // write idx record
        record_idx.pos = pos;

        if ((ret = ldb_append_record_idx(obj, &new_state, &record_idx)) != LDB_OK)
            exit_function(ret);

        pos += rec_len;
        valid_end = pos;
    }

    if (fflush(obj->idx_fp) != 0)
        exit_function(LDB_ERR_WRITE_IDX);

    // Step 3: Update state
    obj->state = new_state;
    obj->dat_end = valid_end;

    if (fseek(obj->dat_fp, 0, SEEK_END) == -1)
        exit_function(LDB_ERR_READ_DAT);

    if (fseek(obj->idx_fp, 0, SEEK_END) == -1)
        exit_function(LDB_ERR_READ_IDX);

    return LDB_OK;

END_FUNCTION:
    if (obj->idx_fp != NULL) {
        fclose(obj->idx_fp);
        obj->idx_fp = NULL;
    }
    return ret;
}

#define goto_zeroize(file_pos) \
    do { \
        pos = file_pos; \
        goto ZEROIZE; \
    } while (0)

/**
 * Scans all data records verifying checksums and sequence numbers.
 * If repair is true and trailing data is detected, it is zeroed out.
 * Non-repairable errors (checksum, seqnum gap) are returned regardless of repair.
 *
 * @pre Requires obj->dat_fp to be valid and caller holds mutex_files.
 *
 * @param[in]  obj       Journal to validate.
 * @param[in]  repair    If true, attempt to repair trailing dat data.
 *
 * @return Error code (0 = OK, data file is consistent).
 */
static int ldb_check_dat(ldb_impl_t *obj, bool repair)
{
    int ret = LDB_OK;
    int dat_fd = fileno(obj->dat_fp);
    ldb_record_dat_t record_dat = {0};
    size_t pos = sizeof(ldb_header_dat_t);
    size_t dat_len = 0;
    uint64_t prev_seqnum = 0;
    bool has_issues = false;
    bool is_repaired = false;

    ldb_reset_state(&obj->state);
    obj->dat_end = pos;

    dat_len = ldb_get_file_size(obj->dat_fp);

    // scan all dat records
    while (pos + sizeof(ldb_record_dat_t) <= dat_len)
    {
        ret = ldb_read_record_dat(dat_fd, pos, &record_dat, true);

        if (ret != LDB_OK && ret != LDB_ERR_CORRUPT_DAT && ret != LDB_ERR_CHECKSUM) {
            has_issues = true;
            exit_function(ret);
        }

        if (ret == LDB_ERR_CORRUPT_DAT)
        {
            goto_zeroize(pos);
        }
        else if (record_dat.seqnum == 0)
        {
            goto_zeroize(pos);
        }
        else if (ret == LDB_ERR_CHECKSUM)
        {
            has_issues = true;
            goto_zeroize(pos);
        }

        if (prev_seqnum != 0 && record_dat.seqnum != prev_seqnum + 1)
        {
            has_issues = true;
            goto_zeroize(pos);
        }

        prev_seqnum = record_dat.seqnum;

        pos += sizeof(ldb_record_dat_t) + record_dat.data_len + ldb_padding(record_dat.data_len);

        if (obj->state.min_seqnum == 0)
        {
            obj->state.min_seqnum = record_dat.seqnum;
        }

        obj->state.max_seqnum = record_dat.seqnum;
        obj->dat_end = pos;
    }

ZEROIZE:
    if (ldb_is_zeroized(obj->dat_fp, pos))
        exit_function(LDB_OK);

    has_issues = true;

    if (repair)
    {
        if (obj->read_only)
            exit_function(LDB_ERR_READONLY);

        if (!ldb_zeroize(obj->dat_fp, pos))
            exit_function(LDB_ERR_WRITE_DAT);

        is_repaired = true;
    }

END_FUNCTION:
    return (has_issues ? (is_repaired ? LDB_OK : ret) : LDB_OK);
}

/**
 * Cross-validates the index file against the data file of a journal.
 *
 * Assumes obj->dat_fp is open and the data file has already been successfully 
 * validated.
 * 
 * If repair is true and any mismatch is found, the index file is rebuilt.
 *
 * This function does not use ldb_open_idx() because can hide some checks.
 * 
 * @pre Requires obj->dat_fp to be valid.
 *
 * @param[in]  obj       Journal to validate.
 * @param[in]  repair    If true, rebuild the index file on any mismatch.
 *
 * @return Error code (0 = OK, index file is consistent).
 */
static int ldb_check_idx(ldb_impl_t *obj, bool repair)
{
    ssize_t rc = 0;
    int ret = LDB_OK;
    int dat_fd = fileno(obj->dat_fp);
    int idx_fd = fileno(obj->idx_fp);
    ldb_record_dat_t record_dat = {0};
    ldb_record_idx_t record_idx = {0};
    size_t pos = sizeof(ldb_header_idx_t);
    size_t dat_len = 0;
    size_t idx_len = 0;
    size_t count = 0;
    uint64_t min_seqnum = 0;
    bool has_issues = false;
    bool is_repaired = false;

    dat_len = ldb_get_file_size(obj->dat_fp);
    idx_len = ldb_get_file_size(obj->idx_fp);

    min_seqnum = obj->state.min_seqnum;

    // empty journal
    if (min_seqnum == 0)
        goto_zeroize(sizeof(ldb_header_idx_t));

    // scan all idx records
    while (pos + sizeof(ldb_record_idx_t) <= idx_len)
    {
        rc = pread(idx_fd, &record_idx, sizeof(ldb_record_idx_t), (off_t)pos);

        if (rc == -1) {
            has_issues = true;
            exit_function(LDB_ERR_READ_IDX);
        }

        if (rc != (ssize_t)sizeof(ldb_record_idx_t))
            goto_zeroize(pos);

        if (record_idx.pos == 0)
            break;

        if (record_idx.pos < sizeof(ldb_header_dat_t) || record_idx.pos > dat_len)
        {
            has_issues = true;
            exit_function(LDB_ERR_CORRUPT_IDX);
        }

        ret = ldb_read_record_dat(dat_fd, record_idx.pos, &record_dat, true);

        if (ret != LDB_OK)
        {
            has_issues = true;
            exit_function(LDB_ERR_CORRUPT_IDX);
        }

        if (record_dat.seqnum != min_seqnum + count)
        {
            has_issues = true;
            exit_function(LDB_ERR_CORRUPT_IDX);
        }

        pos += sizeof(ldb_record_idx_t);
        count++;

        if (record_dat.seqnum == obj->state.max_seqnum)
            goto_zeroize(pos);
    }

    if (min_seqnum + count - 1 != obj->state.max_seqnum)
    {
        has_issues = true;
        exit_function(LDB_ERR_CORRUPT_IDX);
    }

ZEROIZE:
    if (ldb_is_zeroized(obj->idx_fp, pos))
        return LDB_OK;

    if (repair)
    {
        if (obj->read_only)
            return LDB_ERR_READONLY;

        if (!ldb_zeroize(obj->idx_fp, pos))
            return LDB_ERR_WRITE_IDX;

        return LDB_OK;
    }

    return LDB_ERR_CORRUPT_IDX;

END_FUNCTION:
    if (has_issues && repair && !is_repaired)
    {
        if (obj->read_only)
        {
            ret = LDB_ERR_READONLY;
        }
        else if ((ret = ldb_rebuild_idx(obj)) == LDB_OK)
        {
            is_repaired = true;
        }
    }

    return (has_issues ? (is_repaired ? LDB_OK : ret) : LDB_OK);
}

int ldb_check(ldb_journal_t *obj, bool repair)
{
    if (!obj)
        return LDB_ERR_ARG;

    if (!ldb_is_valid_obj(obj))
        return LDB_ERR;

    pthread_mutex_lock(&obj->mutex_files);
    pthread_mutex_lock(&obj->mutex_state);

    int ret = LDB_OK;

    if ((ret = ldb_check_dat(obj, repair)) != LDB_OK)
        goto END_FUNCTION;

    if ((ret = ldb_check_idx(obj, repair)) != LDB_OK)
        goto END_FUNCTION;

END_FUNCTION:
    pthread_mutex_unlock(&obj->mutex_state);
    pthread_mutex_unlock(&obj->mutex_files);
    return ret;
}

#undef goto_zeroize

int ldb_split(const char *path, const char *name, uint64_t seqnum, const char *name_a, const char *name_b)
{
    int ret = LDB_OK;
    ldb_impl_t obj = {0};
    ldb_header_dat_t header_dat = {0};
    ldb_header_idx_t header_idx = {0};
    ldb_record_idx_t record_idx = {0};
    ldb_record_idx_t *records_b = NULL;
    char *filename_dat_a = NULL;
    char *filename_dat_b = NULL;
    char *filename_idx_a = NULL;
    char *filename_idx_b = NULL;
    FILE *fp_dat_a = NULL;
    FILE *fp_dat_b = NULL;
    FILE *fp_idx_a = NULL;
    FILE *fp_idx_b = NULL;
    int dat_fd = -1;
    int idx_fd = -1;
    size_t end_idx_a = 0;
    size_t count_b = 0;
    size_t size_idx_b = 0;
    size_t dat_offset = 0;

    // Validate input parameters
    if (!ldb_is_valid_name(name) || !ldb_is_valid_name(name_a) || !ldb_is_valid_name(name_b))
        exit_function(LDB_ERR_ARG);

    if (strcmp(name, name_a) == 0 || strcmp(name, name_b) == 0 || strcmp(name_a, name_b) == 0)
        exit_function(LDB_ERR_ARG); 

    if ((filename_dat_a = ldb_create_filename(path, name_a, LDB_EXT_DAT)) == NULL)
        exit_function(LDB_ERR_MEM);

    if ((filename_dat_b = ldb_create_filename(path, name_b, LDB_EXT_DAT)) == NULL)
        exit_function(LDB_ERR_MEM);

    if ((filename_idx_a = ldb_create_filename(path, name_a, LDB_EXT_IDX)) == NULL)
        exit_function(LDB_ERR_MEM);

    if ((filename_idx_b = ldb_create_filename(path, name_b, LDB_EXT_IDX)) == NULL)
        exit_function(LDB_ERR_MEM);

    // Open original journal
    if ((ret = ldb_open(&obj, path, name, 0)) != LDB_OK)
        exit_function(ret);

    dat_fd = fileno(obj.dat_fp);
    idx_fd = fileno(obj.idx_fp);

    if (seqnum >= obj.state.max_seqnum)
        exit_function(LDB_ERR_ARG);

    // Read file headers
    if (pread(dat_fd, &header_dat, sizeof(header_dat), 0) != (ssize_t)sizeof(header_dat))
        exit_function(LDB_ERR_READ_DAT);

    if (pread(idx_fd, &header_idx, sizeof(header_idx), 0) != (ssize_t)sizeof(header_idx))
        exit_function(LDB_ERR_READ_IDX);

    // Create journal A (seqnum1 .. seqnum)
    if ((fp_dat_a = fopen(filename_dat_a, "wx")) == NULL)
        exit_function(LDB_ERR_CREATE_DAT);

    if ((ret = ldb_read_record_idx(idx_fd, &obj.state, seqnum + 1, &record_idx)) != LDB_OK)
        exit_function(ret);

    if (!ldb_copy_file(obj.dat_fp, 0, record_idx.pos, fp_dat_a, 0))
        exit_function(LDB_ERR_WRITE_DAT);

    if (fclose(fp_dat_a) != 0)
        exit_function(LDB_ERR_WRITE_DAT);

    fp_dat_a = NULL;

    // Create journal B (seqnum+1 .. seqnum2)
    if ((fp_dat_b = fopen(filename_dat_b, "wx")) == NULL)
        exit_function(LDB_ERR_CREATE_DAT);

    if (fwrite(&header_dat, sizeof(ldb_header_dat_t), 1, fp_dat_b) != 1)
        exit_function(LDB_ERR_WRITE_DAT);

    if (!ldb_copy_file(obj.dat_fp, record_idx.pos, obj.dat_end, fp_dat_b, sizeof(ldb_header_dat_t)))
        exit_function(LDB_ERR_WRITE_DAT);

    if (fclose(fp_dat_b) != 0)
        exit_function(LDB_ERR_WRITE_DAT);

    fp_dat_b = NULL;

    // Generate index for journal A
    if ((fp_idx_a = fopen(filename_idx_a, "wx")) == NULL)
        exit_function(LDB_ERR_CREATE_IDX);

    end_idx_a = sizeof(ldb_header_idx_t) + (size_t)(seqnum - obj.state.min_seqnum + 1) * sizeof(ldb_record_idx_t);

    if (!ldb_copy_file(obj.idx_fp, 0, end_idx_a, fp_idx_a, 0))
        exit_function(LDB_ERR_WRITE_IDX);

    if (fclose(fp_idx_a) != 0)
        exit_function(LDB_ERR_WRITE_IDX);

    fp_idx_a = NULL;

    // Generate index for journal B
    count_b = (size_t)(obj.state.max_seqnum - seqnum);
    size_idx_b = count_b * sizeof(ldb_record_idx_t);
    dat_offset = record_idx.pos - sizeof(ldb_header_dat_t);

    if ((records_b = malloc(size_idx_b)) == NULL)
        exit_function(LDB_ERR_MEM);

    if (pread(idx_fd, records_b, size_idx_b, (off_t)end_idx_a) != (ssize_t)size_idx_b)
        exit_function(LDB_ERR_READ_IDX);

    for (size_t i = 0; i < count_b; i++)
        records_b[i].pos -= dat_offset;

    header_idx.first_seqnum = seqnum + 1;

    if ((fp_idx_b = fopen(filename_idx_b, "wx")) == NULL)
        exit_function(LDB_ERR_CREATE_IDX);

    if (fwrite(&header_idx, sizeof(header_idx), 1, fp_idx_b) != 1)
        exit_function(LDB_ERR_WRITE_IDX);

    if (fwrite(records_b, sizeof(ldb_record_idx_t), count_b, fp_idx_b) != count_b)
        exit_function(LDB_ERR_WRITE_IDX);

    if (fclose(fp_idx_b) != 0)
        exit_function(LDB_ERR_WRITE_IDX);

    fp_idx_b = NULL;

    // Remove original journal (dat and idx)
    remove(obj.dat_path);
    remove(obj.idx_path);

    ret = LDB_OK;

END_FUNCTION:
    ldb_close(&obj);
    if (fp_dat_a != NULL) fclose(fp_dat_a);
    if (fp_dat_b != NULL) fclose(fp_dat_b);
    if (fp_idx_a != NULL) fclose(fp_idx_a);
    if (fp_idx_b != NULL) fclose(fp_idx_b);
    if (ret != LDB_OK) {
        if (filename_dat_a) remove(filename_dat_a);
        if (filename_dat_b) remove(filename_dat_b);
        if (filename_idx_a) remove(filename_idx_a);
        if (filename_idx_b) remove(filename_idx_b);
    }
    free(filename_dat_a);
    free(filename_dat_b);
    free(filename_idx_a);
    free(filename_idx_b);
    free(records_b);
    return ret;
}

int ldb_join(const char *path, const char *name1, const char *name2, const char *name)
{
    int ret = LDB_OK;
    ldb_impl_t obj1 = {0};
    ldb_impl_t obj2 = {0};
    ldb_header_dat_t header_dat = {0};
    ldb_record_idx_t *records_idx = NULL;
    char *filename_dat_out = NULL;
    char *filename_idx_out = NULL;
    FILE *fp_dat_out = NULL;
    FILE *fp_idx_out = NULL;
    int dat_fd1 = -1;

    if (!path)
        exit_function(LDB_ERR_ARG);

    if (!ldb_is_valid_name(name1) || !ldb_is_valid_name(name2) || !ldb_is_valid_name(name))
        exit_function(LDB_ERR_ARG);

    if (strcmp(name1, name2) == 0 || strcmp(name1, name) == 0 || strcmp(name2, name) == 0)
        exit_function(LDB_ERR_ARG);

    if ((filename_dat_out = ldb_create_filename(path, name, LDB_EXT_DAT)) == NULL)
        exit_function(LDB_ERR_MEM);

    if ((filename_idx_out = ldb_create_filename(path, name, LDB_EXT_IDX)) == NULL)
        exit_function(LDB_ERR_MEM);

    if ((ret = ldb_open(&obj1, path, name1, 0)) != LDB_OK)
        exit_function(ret);

    if ((ret = ldb_open(&obj2, path, name2, 0)) != LDB_OK)
        exit_function(ret);

    dat_fd1 = fileno(obj1.dat_fp);

    if (pread(dat_fd1, &header_dat, sizeof(header_dat), 0) != (ssize_t)sizeof(header_dat))
        exit_function(LDB_ERR_READ_DAT);

    // check consecutiveness only when both journals have entries
    if (obj1.state.min_seqnum != 0 && obj2.state.min_seqnum != 0) {
        if (obj1.state.max_seqnum + 1 != obj2.state.min_seqnum)
            exit_function(LDB_ERR_SEQNUM);
    }

    if ((fp_dat_out = fopen(filename_dat_out, "wx")) == NULL)
        exit_function(LDB_ERR_CREATE_DAT);

    if (fwrite(&header_dat, sizeof(ldb_header_dat_t), 1, fp_dat_out) != 1)
        exit_function(LDB_ERR_WRITE_DAT);

    if (obj1.state.min_seqnum != 0) {
        if (!ldb_copy_file(obj1.dat_fp, sizeof(ldb_header_dat_t), obj1.dat_end, fp_dat_out, sizeof(ldb_header_dat_t)))
            exit_function(LDB_ERR_WRITE_DAT);
    }

    if (obj2.state.min_seqnum != 0) {
        size_t pos_out = (obj1.state.min_seqnum != 0) ? obj1.dat_end : sizeof(ldb_header_dat_t);
        if (!ldb_copy_file(obj2.dat_fp, sizeof(ldb_header_dat_t), obj2.dat_end, fp_dat_out, pos_out))
            exit_function(LDB_ERR_WRITE_DAT);
    }

    if (fclose(fp_dat_out) != 0)
        exit_function(LDB_ERR_WRITE_DAT);

    fp_dat_out = NULL;

    // Generate index for output journal
    fp_idx_out = fopen(filename_idx_out, "wx");
    if (fp_idx_out == NULL)
        exit_function(LDB_ERR_CREATE_IDX);

    if (obj1.state.min_seqnum == 0 && obj2.state.min_seqnum == 0)
    {
        // Both empty: copy header with first_seqnum = 0
        ldb_header_idx_t hdr_idx = {0};
        if (pread(fileno(obj1.idx_fp), &hdr_idx, sizeof(hdr_idx), 0) != (ssize_t)sizeof(hdr_idx))
            exit_function(LDB_ERR_READ_IDX);
        hdr_idx.first_seqnum = 0;
        if (fwrite(&hdr_idx, sizeof(hdr_idx), 1, fp_idx_out) != 1)
            exit_function(LDB_ERR_WRITE_IDX);
    }
    else if (obj1.state.min_seqnum == 0)
    {
        // Only journal2 has data: copy idx2 entirely (positions unchanged)
        size_t idx2_end = sizeof(ldb_header_idx_t) +
            (size_t)(obj2.state.max_seqnum - obj2.state.min_seqnum + 1) * sizeof(ldb_record_idx_t);
        if (!ldb_copy_file(obj2.idx_fp, 0, idx2_end, fp_idx_out, 0))
            exit_function(LDB_ERR_WRITE_IDX);
    }
    else if (obj2.state.min_seqnum == 0)
    {
        // Only journal1 has data: copy idx1 entirely
        size_t idx1_end = sizeof(ldb_header_idx_t) +
            (size_t)(obj1.state.max_seqnum - obj1.state.min_seqnum + 1) * sizeof(ldb_record_idx_t);
        if (!ldb_copy_file(obj1.idx_fp, 0, idx1_end, fp_idx_out, 0))
            exit_function(LDB_ERR_WRITE_IDX);
    }
    else
    {
        // Both have data: copy idx1, then read idx2 into memory, adjust offsets, append
        size_t count1      = (size_t)(obj1.state.max_seqnum - obj1.state.min_seqnum + 1);
        size_t count2      = (size_t)(obj2.state.max_seqnum - obj2.state.min_seqnum + 1);
        size_t idx1_end    = sizeof(ldb_header_idx_t) + count1 * sizeof(ldb_record_idx_t);
        size_t idx2_size   = count2 * sizeof(ldb_record_idx_t);
        size_t dat_offset2 = obj1.dat_end - sizeof(ldb_header_dat_t);

        if (!ldb_copy_file(obj1.idx_fp, 0, idx1_end, fp_idx_out, 0))
            exit_function(LDB_ERR_WRITE_IDX);

        if ((records_idx = malloc(idx2_size)) == NULL)
            exit_function(LDB_ERR_MEM);

        if (pread(fileno(obj2.idx_fp), records_idx, idx2_size, (off_t)sizeof(ldb_header_idx_t)) != (ssize_t)idx2_size)
            exit_function(LDB_ERR_READ_IDX);

        for (size_t i = 0; i < count2; i++)
            records_idx[i].pos += dat_offset2;

        if (fseek(fp_idx_out, 0, SEEK_END) != 0)
            exit_function(LDB_ERR_WRITE_IDX);

        if (fwrite(records_idx, sizeof(ldb_record_idx_t), count2, fp_idx_out) != count2)
            exit_function(LDB_ERR_WRITE_IDX);
    }

    if (fclose(fp_idx_out) != 0)
        exit_function(LDB_ERR_WRITE_IDX);

    fp_idx_out = NULL;

    // Remove source journals
    remove(obj1.dat_path);
    remove(obj1.idx_path);
    remove(obj2.dat_path);
    remove(obj2.idx_path);

    ret = LDB_OK;

END_FUNCTION:
    ldb_close(&obj1);
    ldb_close(&obj2);
    if (fp_dat_out != NULL) fclose(fp_dat_out);
    if (fp_idx_out != NULL) fclose(fp_idx_out);
    if (ret != LDB_OK) {
        if (filename_dat_out) remove(filename_dat_out);
        if (filename_idx_out) remove(filename_idx_out);
    }
    free(filename_dat_out);
    free(filename_idx_out);
    free(records_idx);
    return ret;
}

const char * ldb_version(void)
{
    return LDB_STR(LDB_VERSION_MAJOR) "." LDB_STR(LDB_VERSION_MINOR) "." LDB_STR(LDB_VERSION_PATCH);
}

int ldb_open(ldb_impl_t *obj, const char *path, const char *name, int flags)
{
    int ret = LDB_OK;

    if ((ret = ldb_init(obj, path, name, flags)) != LDB_OK)
        return ret;

    // case dat file not exist
    if (access(obj->dat_path, F_OK) != 0)
    {
        if (!(flags & LDB_OPEN_CREATE))
            exit_function(LDB_ERR_NOFILE_DAT);

        // READONLY does not apply in this case

        if (!ldb_create_dat(obj->dat_path))
            exit_function(LDB_ERR_CREATE_DAT);

        if (!ldb_create_idx(obj->idx_path))
            exit_function(LDB_ERR_CREATE_IDX);
    }

    // open data file
    if ((ret = ldb_open_dat(obj)) != LDB_OK)
        exit_function(ret);

    // case idx file not exist
    if (access(obj->idx_path, F_OK) != 0)
    {
        if (flags & LDB_OPEN_READONLY)
            exit_function(LDB_ERR_NOFILE_IDX);
    }

    // open index file (may not exist)
    if ((ret = ldb_open_idx(obj)) != LDB_OK)
    {
        if (ret != LDB_ERR_OPEN_IDX && ret != LDB_ERR_CORRUPT_IDX)
            exit_function(ret);

        if (flags & LDB_OPEN_READONLY)
            exit_function(ret);

        if ((ret = ldb_rebuild_idx(obj)) != LDB_OK)
            exit_function(ret);
    }

    assert(!feof(obj->dat_fp));
    assert(!feof(obj->idx_fp));
    assert(!ferror(obj->dat_fp));
    assert(!ferror(obj->idx_fp));

    return LDB_OK;

END_FUNCTION:
    ldb_close(obj);
    return ret;
}

int ldb_append(ldb_impl_t *obj, ldb_entry_t *entries, size_t len, size_t *num)
{
    if (num != NULL)
        *num = 0;

    if (!obj || !entries)
        return LDB_ERR_ARG;

    if (obj->read_only)
        return LDB_ERR_READONLY;

    if (!ldb_is_valid_obj(obj))
        return LDB_ERR;

    if (len == 0)
        return LDB_OK;

    size_t i;
    int ret = LDB_OK;
    ldb_range_t state;

    pthread_mutex_lock(&obj->mutex_state);
    state = obj->state;
    pthread_mutex_unlock(&obj->mutex_state);

    if (fseek(obj->dat_fp, (long)obj->dat_end, SEEK_SET) != 0)
        return LDB_ERR_WRITE_DAT;

    size_t pos = ldb_get_pos_idx(&state, state.max_seqnum + 1);
    if (fseek(obj->idx_fp, (long)pos, SEEK_SET) != 0)
        return LDB_ERR_WRITE_IDX;

    for (i = 0; i < len; i++)
    {
        if (entries[i].seqnum == 0)
            entries[i].seqnum = state.max_seqnum + 1;

        ldb_record_idx_t record_idx = {
            .pos = obj->dat_end
        };

        if ((ret = ldb_append_entry_dat(obj, &state, &entries[i])) != LDB_OK)
            break;

        if ((ret = ldb_append_record_idx(obj, &state, &record_idx)) != LDB_OK)
            break;

        if (num != NULL)
            (*num)++;
    }

    if (i == 0)
        return ret;

    if (fflush(obj->dat_fp) != 0)
        ret = (ret == LDB_OK ? LDB_ERR_WRITE_DAT : ret);

    if (fflush(obj->idx_fp) != 0)
        ret = (ret == LDB_OK ? LDB_ERR_WRITE_IDX : ret);

    if (obj->force_fsync && fdatasync(fileno(obj->dat_fp)) == -1)
        ret = (ret == LDB_OK ? LDB_ERR_WRITE_DAT : ret);

    pthread_mutex_lock(&obj->mutex_state);
    obj->state = state;
    pthread_mutex_unlock(&obj->mutex_state);

    return ret;
}

int ldb_read(ldb_journal_t *obj, uint64_t seqnum, ldb_entry_t *entries, size_t len, char *buf, size_t buf_len, size_t *num)
{
    if (num != NULL)
        *num = 0;

    if (!obj || !entries || len == 0 || !buf || buf_len < sizeof(ldb_record_dat_t))
        return LDB_ERR_ARG;

    memset(entries, 0x00, len * sizeof(ldb_entry_t));

    pthread_mutex_lock(&obj->mutex_files);

    int ret = LDB_ERR;
    int dat_fd = -1;
    int idx_fd = -1;
    uint64_t read_pos = 0;
    uint64_t read_bytes = 0;
    ldb_range_t state = {0};
    ldb_record_idx_t record_idx = {0};
    const ldb_record_dat_t *record_dat_ptr = NULL;
    size_t padding = 0;
    ssize_t bytes = 0;
    uint64_t seq = 0;
    size_t idx = 0;

    if (!ldb_is_valid_obj(obj))
        exit_function(LDB_ERR);

    dat_fd = fileno(obj->dat_fp);
    idx_fd = fileno(obj->idx_fp);

    pthread_mutex_lock(&obj->mutex_state);
    state = obj->state;
    pthread_mutex_unlock(&obj->mutex_state);

    if (seqnum == 0 || seqnum < state.min_seqnum || seqnum > state.max_seqnum)
        exit_function(LDB_ERR_NOT_FOUND);

    if ((ret = ldb_read_record_idx(idx_fd, &state, seqnum, &record_idx)) != LDB_OK)
        exit_function(ret);

    read_pos = record_idx.pos;

    if (seqnum + len <= state.max_seqnum)
    {
        if ((ret = ldb_read_record_idx(idx_fd, &state, seqnum + len, &record_idx)) != LDB_OK)
            exit_function(ret);

        assert(record_idx.pos > read_pos);
        read_bytes = ldb_min(record_idx.pos - read_pos, buf_len);
    }
    else
    {
        read_bytes = buf_len;
    }

    bytes = pread(dat_fd, buf, read_bytes, (off_t)read_pos);

    if (bytes == -1)
        exit_function(LDB_ERR_READ_DAT);

    if (bytes < (ssize_t)sizeof(ldb_record_dat_t))
        exit_function(LDB_ERR_CORRUPT_DAT);

    seq = seqnum - 1;

    while (idx < len && seq < state.max_seqnum)
    {
        if (bytes < (ssize_t)sizeof(ldb_record_dat_t))
        {
            // In this skewed case (buffer overflow and read() ending in the 
            // middle of a record), we invalidate the previous entry (that 
            // was succesfully read). This avoid us from doing an additional
            // reading and allows us to notify the caller that the buffer
            // is too small.

            assert(idx > 0);
            entries[idx - 1].data = NULL;
            idx--;
            break;
        }

        record_dat_ptr = (ldb_record_dat_t *)buf;

        assert(seq + 1 == record_dat_ptr->seqnum);

        entries[idx].seqnum = record_dat_ptr->seqnum;
        entries[idx].data_len = record_dat_ptr->data_len;
        entries[idx].data = buf + sizeof(ldb_record_dat_t);

        assert(((uintptr_t)entries[idx].data) % sizeof(uintptr_t) == 0);

        buf += sizeof(ldb_record_dat_t);
        bytes -= (ssize_t)sizeof(ldb_record_dat_t);

        if (bytes < (ssize_t)record_dat_ptr->data_len) {
            entries[idx].data = NULL;
            break;
        }

        buf += record_dat_ptr->data_len;
        bytes -= record_dat_ptr->data_len;

        padding = ldb_min(ldb_padding(record_dat_ptr->data_len), (size_t)bytes);

        buf += padding;
        bytes -= (ssize_t)padding;

        seq = record_dat_ptr->seqnum;
        idx++;
    }

    if (num != NULL)
        *num = idx;

    ret = LDB_OK;

END_FUNCTION:
    pthread_mutex_unlock(&obj->mutex_files);
    return ret;
}

ldb_range_t ldb_get_range(ldb_impl_t *obj)
{
    if (!obj)
        return (ldb_range_t){UINT64_MAX, UINT64_MAX};

    if (!ldb_is_valid_obj(obj))
        return (ldb_range_t){UINT64_MAX, UINT64_MAX};

    ldb_range_t range = {0};

    pthread_mutex_lock(&obj->mutex_state);
    range = obj->state;
    pthread_mutex_unlock(&obj->mutex_state);

    return range;
}

long ldb_rollback(ldb_impl_t *obj, uint64_t seqnum)
{
    if (!obj)
        return LDB_ERR_ARG;

    if (obj->read_only)
        return LDB_ERR_READONLY;

    pthread_mutex_lock(&obj->mutex_files);

    long ret = LDB_ERR;
    long removed_entries = 0;
    ldb_range_t state = {0};
    ldb_record_idx_t record_idx = {0};
    size_t dat_end_new = sizeof(ldb_header_dat_t);
    size_t idx_end_new = sizeof(ldb_header_idx_t);
    int idx_fd = -1;

    if (!ldb_is_valid_obj(obj))
        exit_function(LDB_ERR);

    idx_fd = fileno(obj->idx_fp);

    pthread_mutex_lock(&obj->mutex_state);
    state = obj->state;
    pthread_mutex_unlock(&obj->mutex_state);

    // case nothing to rollback
    if (state.min_seqnum == 0 || state.max_seqnum <= seqnum)
        exit_function(0);

    removed_entries = (long)state.max_seqnum - (long)ldb_max(seqnum, state.min_seqnum - 1);

    if (seqnum >= state.min_seqnum)
    {
        if ((ret = ldb_read_record_idx(idx_fd, &state, seqnum + 1, &record_idx)) != LDB_OK)
            exit_function(ret);

        dat_end_new = record_idx.pos;
        idx_end_new = ldb_get_pos_idx(&state, seqnum + 1);
    }

    // set index entries to 0
    if (!ldb_zeroize(obj->idx_fp, idx_end_new))
        exit_function(LDB_ERR_WRITE_IDX);

    if (fflush(obj->idx_fp) != 0)
        exit_function(LDB_ERR_WRITE_IDX);

    // update status
    if (seqnum < state.min_seqnum)
    {
        state.min_seqnum = 0;
        state.max_seqnum = 0;
        obj->dat_end = sizeof(ldb_header_dat_t);

        if ((ret = ldb_write_idx_seqnum(obj, 0)) != LDB_OK)
            exit_function(ret);
    }
    else
    {
        state.max_seqnum = seqnum;
        obj->dat_end = dat_end_new;
    }

    pthread_mutex_lock(&obj->mutex_state);
    obj->state = state;
    pthread_mutex_unlock(&obj->mutex_state);

    // set data entries to 0
    if (!ldb_zeroize(obj->dat_fp, dat_end_new))
        exit_function(LDB_ERR_WRITE_DAT);

    if (fflush(obj->dat_fp) != 0)
        exit_function(LDB_ERR_WRITE_DAT);

    if (obj->force_fsync && fdatasync(fileno(obj->dat_fp)) == -1)
        exit_function(LDB_ERR_WRITE_DAT);

    ret = removed_entries;

END_FUNCTION:
    pthread_mutex_unlock(&obj->mutex_files);
    return ret;
}

ldb_journal_t * ldb_alloc(void) {
    return (ldb_journal_t *)calloc(1, sizeof(ldb_impl_t));
}

void ldb_free(ldb_journal_t *obj) {
    free(obj);
}

int ldb_set_meta(ldb_journal_t *obj, const char *meta, size_t len)
{
    static const char zero[LDB_METADATA_LEN] = {0};

    if (!obj || !meta || len > LDB_METADATA_LEN)
        return LDB_ERR_ARG;

    if (obj->read_only)
        return LDB_ERR_READONLY;

    if (!ldb_is_valid_obj(obj))
        return LDB_ERR;

    fflush(obj->dat_fp);

    int dat_fd = fileno(obj->dat_fp);
    off_t pos = offsetof(ldb_header_dat_t, metadata);

    if (pwrite(dat_fd, meta, len, pos) != (ssize_t)len)
        return LDB_ERR_WRITE_DAT;

    if (len < LDB_METADATA_LEN)
    {
        pos += (off_t)len;
        len = LDB_METADATA_LEN - len;

        if (pwrite(dat_fd, zero, len, pos) != (ssize_t)len)
            return LDB_ERR_WRITE_DAT;
    }

    return LDB_OK;
}

int ldb_get_meta(ldb_journal_t *obj, char *meta, size_t len)
{
    if (!obj || !meta || len > LDB_METADATA_LEN)
        return LDB_ERR_ARG;

    if (!ldb_is_valid_obj(obj))
        return LDB_ERR;

    ssize_t rc = 0;
    int dat_fd = fileno(obj->dat_fp);
    off_t pos = offsetof(ldb_header_dat_t, metadata);

    rc = pread(dat_fd, meta, len, pos);

    if (rc == -1)
        return LDB_ERR_READ_DAT;

    if (rc != (ssize_t)len)
        return LDB_ERR_CORRUPT_DAT;

    return LDB_OK;
}

#undef LDB_FREE_STR
#undef exit_function
